apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: perfume-cart-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          env:
            - name: PORT
              value: "7001"
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "cart_db"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: ClusterIP
  ports:
    - port: 7001
      targetPort: 7001
  selector:
    app: cart-service
